apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "mongo.printSharedLabels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        {{- include "mongo.printSharedLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mongo
        image: mongo:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        volumeMounts:
        - name: {{ .Release.Name }}-volume
          mountPath: /mongo/data
      volumes:
      - name: {{ .Release.Name }}-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-persistent-volume-claim