apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "mongo.printSharedLabels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        {{- include "mongo.printSharedLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mongo
        image: mongo:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/mongo
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests: 
          storage: 5Gi