version: 2
updates:
  - package-ecosystem: 'npm'
    directory: ./fitness-ui
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    labels:
      - fitness-ui
  - package-ecosystem: 'gradle'
    directory: ./fitness-server
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    labels:
      - fitness-server
