gateway:
  routes:
  - name: fitness-server
    prefix: /fitness/api
    redirect:
      namespace: default
      service: fitness-server-service
    rewrite:
      source: /fitness/api(/|$)(.*)
      target: /api/$2
  - name: mongo-rest-adapter
    prefix: /mongo/api
    redirect:
      namespace: default
      service: mongo-rest-adapter-service
    rewrite:
      source: /mongo/api(/|$)(.*)
      target: /api/$2
