apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-map
  labels:
    {{ include "mongo-rest-adapter.printSharedLabels" . | nindent 4 }}
data:
  APPLICATION_MONGO_URL: {{ .Values.mongo.service }}.{{ .Values.mongo.namespace }}.svc.cluster.local:{{ .Values.mongo.port }}