apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "mongo-rest-adapter.printSharedLabels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongo-rest-adapter
  template:
    metadata:
      labels:
        app: mongo-rest-adapter
        {{- include "mongo-rest-adapter.printSharedLabels" . | nindent 8 }}
    spec:
      containers:
        - name: server
          image: irdcat/mongo-rest-adapter:{{ .Chart.AppVersion }}
          command: ["java"]
          args:
            - -jar
            - server.jar
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config-map
          ports:
              - containerPort: 8080
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}