apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "mongo-rest-adapter.printSharedLabels" . | nindent 4 }}
spec:
  selector:
    app: mongo-rest-adapter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP