{{- if eq .Values.development true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external-service
  labels:
  {{- include "k8s-mongo.printSharedLabels" . | nindent 4 }}
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32017
  type: NodePort
{{- end }}