apiVersion: v1
kind: Service
metadata:
  name: mongo-internal
  {{- include "k8s-mongo.printSharedLabels" . | nindent 2 }}
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP