apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-persistent-volume
  labels:
  {{- include "k8s-mongo.printSharedLabels" . | nindent 4 }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/mongo"