apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  {{- include "k8s-mongo.printSharedLabels" . | nindent 2 }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclainPolicy: Retain
  hostPath:
    path: "/data/mongo"