apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  {{- include "k8s-mongo.printSharedLabels" . | nindent 2 }}
spec:
  serviceName: mongo-internal
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        {{- include "k8s-mongo.printSharedLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/mongo
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests: 
          storage: 5Gi