spring:
  application:
    name: auth-server
  main:
    allow-bean-definition-overriding: "true"

server:
  port: 8081

logging:
  level:
    root: INFO
    irdcat.auth: DEBUG
    org.springframework.security: TRACE

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html
  show-oauth2-endpoints: true