apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-map
  {{ include "fitness-server.printSharedLabels" . | nindent 2 }}
data:
  SPRING_DATA_MONGODB_HOST: mongo-internal.default.svc.cluster.local
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: fitness
