apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "fitness-ui.printSharedLabels" . | nindent 2 }}
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: fitness-ui
  template:
    metadata:
      name: {{ .Release.Name }}-pod
      labels:
        app: fitness-ui
        {{- include "fitness-ui.printSharedLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: {{ printf "%s:%s" .Values.docker.image .Values.docker.tag }}
          command: ["nginx"]
          args:
            - -g
            - "daemon off;"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config-map
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.5"