apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "fitness-ui.printSharedLabels" . | nindent 4 }}
spec:
  selector:
    app: fitness-ui
  ports:
  - name: http
    port: 3333
    targetPort: 80
  type: LoadBalancer