apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-map
  labels:
    {{ include "api-gateway.printSharedLabels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      application:
        name: api-gateway
      main:
        allow-bean-definition-overriding: true
    server:
      port: 8080
    application:
      services:
        {{- range .Values.gateway.routes }}
        - name: {{ .name }}
          prefix: {{ .prefix }}
          redirectTo: http://{{ .redirect.service }}.{{ .redirect.namespace }}.svc.cluster.local
          {{- if .rewrite }}
          rewriteSpec: 
            source: {{ .rewrite.source }}
            target: {{ .rewrite.target }}
          {{- end }}
        {{- end}}
