apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
  {{- include "api-gateway.printSharedLabels" . | nindent 4 }}
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
