apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-map
  labels:
    {{ include "fitness-server.printSharedLabels" . | nindent 4 }}
data:
  SPRING_DATA_MONGODB_HOST: {{ .Values.mongo.service }}.{{ .Values.mongo.namespace }}.svc.cluster.local
  SPRING_DATA_MONGODB_PORT: {{ .Values.mongo.port | quote }}
  SPRING_DATA_MONGODB_DATABASE: {{ .Values.mongo.database }}
