spring:
  application:
    name: fitness-server
  main:
    allow-bean-definition-overriding: true
  server:
    port: 8080
springdoc:
  pathsToMatch: /fitness/api
  swagger-ui:
    path: /swagger-ui.html