apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  {{- include "fitness-server.printSharedLabels" . | nindent 2 }}
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: fitness-server
  template:
    metadata:
      labels:
        app: fitness-server
        {{- include "fitness-server.printSharedLabels" . | nindent 8 }}
    spec:
      containers:
        - name: server
          image: {{ printf "%s:%s" .Values.docker.image .Values.docker.tag }}
          command: ["java"]
          args:
            - -jar
            - server.jar
          envFrom:
            - configMapRef:
                name: fitness-server-config-map
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.5"