apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
  {{- include "fitness-server.printSharedLabels" . | nindent 4 }}
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /api
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-internal-service
                port:
                  number: 8080