apiVersion: v1
kind: Service
metadata:
  name: fitness-server-service
  {{- include "fitness-server.printSharedLabels" . | nindent 2 }}
spec:
  selector:
    app: fitness-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP