apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-internal-service
  labels:
  {{- include "fitness-server.printSharedLabels" . | nindent 4 }}
spec:
  selector:
    app: fitness-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP