gateway:
  routes:
    - name: fitness-server
      prefix: /fitness/api
      redirect:
        service: fitness-server-service
        namespace: default
      rewrite:
        - source: /fitness/api/summary/(<type>.*)
          target: /api/summary/$\{type}
        - source: /fitness/api/exercises/(<sub>.*)
          target: /api/exercises/$\{sub}
        - source: /fitness/api/trainings
          target: /api/trainings
        - source: /fitness/api/trainings/(<date>.*)
          target: /api/training/$\{date}
        - source: /fitness/api/templates
          target: /api/templates
        - source: /fitness/api/templates/(<id>.*)
          target: /api/templates/$\{id}
    - name: mongo-rest-adapter
      prefix: /mongo/api
      redirect:
        service: mongo-rest-adapter-service
        namespace: default
      rewrite:
        - source: /mongo/api/database
          target: /api/database
        - source: /mongo/api/database/(?<dbname>.*)
          target: /api/database/$\{dbname}
        - source: /mongo/api/database/(<dbname>.*)/collection
          target: /api/database/$\{dbname}/collection
        - source: /mongo/api/database/(<dbname>.*)/collection/(?<colname>.*)
          target: /api/database/$\{dbname}/collection/$\{colname}
        - source: /mongo/api/database/(<dbname>.*)/collection/(<colname>.*)/document
          target: /api/database/$\{dbname}/collection/$\{colname}/document
        - source: /mongo/api/database/(<dbname>.*)/collection/(<colname>.*)/document/(?<docname>.*)
          target: /api/database/$\{dbname}/collection/$\{colname}/document/$\{docname}