name: API Gateway

on:
  pull_request:
    branches: ["master"]
    paths:
      - backend/api-gateway/**
      - .github/workflows/api-gateway.yml

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            backend/api-gateway/*.gradle*
            backend/api-gateway/**/gradle-wrapper.properties

      - name: Setup Gradle cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/api-gateway/**') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Static Analysis
        working-directory: ./backend/api-gateway
        run: ./gradlew detekt

      - name: Test
        working-directory: ./backend/api-gateway
        run: ./gradlew test

      - name: Coverage
        working-directory: ./backend/api-gateway
        run: ./gradlew koverLog

      - name: Docker Context
        working-directory: ./backend/api-gateway
        run: ./gradlew buildDockerContext

      - name: Upload Docker context artifact
        uses: actions/upload-artifact@master
        with:
          name: api-gateway-docker-context
          path: backend/api-gateway/build/dockerContext
          if-no-files-found: error

  docker-build:
    needs: gradle-build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Docker Context artifact
        uses: actions/download-artifact@master
        with:
          name: api-gateway-docker-context
          path: .

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: ${{secrets.DOCKER_USER}}/api-gateway:latest

  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "3.16.1"

      - name: Helm Lint
        run: helm lint .
        working-directory: ./backend/api-gateway/helm
        
      - name: Helm Template
        run: helm template raspi .
        working-directory: ./backend/api-gateway/helm
