name: Fitness Server

on:
  pull_request:
    branches: ["master"]
    paths:
      - fitness-server/**
      - .github/workflows/fitness-server.yml

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASS: ${{secrets.DOCKER_PASS}}
  REPO_NAME: fitness-server

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            fitness-server/*.gradle*
            fitness-server/**/gradle-wrapper.properties

      - name: Setup Gradle cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('fitness-server/**') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Test
        working-directory: ./fitness-server
        run: ./gradlew test

      - name: Coverage
        working-directory: ./fitness-server
        run: ./gradlew koverLog

      - name: Docker Context
        working-directory: ./fitness-server
        run: ./gradlew buildDockerContext

      - name: Upload Docker context artifact
        uses: actions/upload-artifact@master
        with:
          name: dockerContext
          path: fitness-server/build/dockerContext
          if-no-files-found: error

  docker-build:
    needs: gradle-build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Docker Context artifact
        uses: actions/download-artifact@master
        with:
          name: dockerContext
          path: .

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: ${{env.DOCKER_USER}}/${{env.REPO_NAME}}:latest

  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "3.16.1"

      - name: Helm Lint
        run: helm lint .
        working-directory: ./fitness-server/helm
        
      - name: Helm Template
        run: helm template raspi .
        working-directory: ./fitness-server/helm
