name: Fitness UI

on:
  pull_request:
    branches: ["master"]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASS: ${{secrets.DOCKER_PASS}}
  REPO_NAME: fitness-ui

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: fitness-ui/package-lock.json
      - name: Setup NPM cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('fitness-server/**') }}
          restore-keys: ${{ runner.os }}-npm-
      - name: Install Node dependencies
        working-directory: ./fitness-ui
        run: npm install
      - name: Build
        working-directory: ./fitness-ui
        run: npm run build
      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      - name: Docker Build
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{steps.date.outputs.date}}
        working-directory: ./fitness-ui
      - name: Docker Push
        run: docker push $DOCKER_USER/$REPO_NAME:${{steps.date.outputs.date}}