name: Fitness Server

on:
  pull_request:
    branches: ["master"]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASS: ${{secrets.DOCKER_PASS}}
  REPO_NAME: fitness-server

jobs:
  gradle-build:
    runs-on: [ubuntu-latest, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            fitness-server/*.gradle*
            fitness-server/**/gradle-wrapper.properties
      - name: Setup Gradle cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('fitness-server/**') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Test
        working-directory: ./fitness-server
        run: ./gradlew test
      - name: Coverage
        working-directory: ./fitness-server
        run: ./gradlew koverLog
      - name: Docker Context
        run: ./gradlew buildDockerContext
        working-directory: ./fitness-server
      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      - name: Docker Build
        run: |
          docker build . \
          --file Dockerfile \
          --platform linux/arm64 \
          --tag $DOCKER_USER/$REPO_NAME:${{steps.date.outputs.date}}
        working-directory: ./fitness-server/build/dockerContext
      - name: Docker Push
        run: docker push $DOCKER_USER/$REPO_NAME:${{steps.date.outputs.date}}