name: Fitness UI

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: fitness-ui/package-lock.json
      - name: Install Node dependencies
        working-directory: ./fitness-ui
        run: npm install
      - name: Build
        working-directory: ./fitness-ui
        run: npm run build