name: Fitness UI

on:
  pull_request:
    branches: ["master"]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASS: ${{secrets.DOCKER_PASS}}
  REPO_NAME: fitness-ui

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: fitness-ui/package-lock.json

      - name: Setup NPM cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('fitness-server/**') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Node dependencies
        working-directory: ./fitness-ui
        run: npm install

      - name: Build
        working-directory: ./fitness-ui
        run: npm run build

  docker-image:
    needs: npm-build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:fitness-ui"
          platforms: linux/arm64
          push: true
          tags: irdcat/fitness-ui:latest

  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "3.16.1"

      - name: Helm Lint
        run: helm lint .
        working-directory: ./k8s-mongo/helm
        
      - name: Helm Template
        run: helm template raspi .
        working-directory: ./k8s-mongo/helm