name: K8s Mongo

on:
  pull_request:
    branches: ["master"]

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "3.16.1"
      - name: Helm Lint
        run: helm lint .
        working-directory: ./k8s-mongo/helm
      - name: Helm Template
        run: helm template raspi .
        working-directory: ./k8s-mongo/helm