name: Mongo

on:
  pull_request:
    branches: ["master"]
    paths: 
      - backend/mongo/**
      - .github/workflows/mongo.yml

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "3.16.1"
      - name: Helm Lint
        run: helm lint .
        working-directory: ./backend/mongo/helm
      - name: Helm Template
        run: helm template raspi .
        working-directory: ./backend/mongo/helm