name: Mongo UI

on:
  pull_request:
    branches: ["master"]
    paths:
      - frontend/mongo-ui/**
      - .github/workflows/mongo-ui.yml

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/mongo-ui/package-lock.json

      - name: Setup NPM cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/mongo-ui/**') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Node dependencies
        working-directory: ./frontend/mongo-ui
        run: npm install --omit=dev --prefer-offline --no-audit --no-fund --progress=false --loglevel error --force

      - name: Build
        working-directory: ./frontend/mongo-ui
        run: npm run build

      - name: Upload Docker context artifact
        uses: actions/upload-artifact@master
        with:
          name: mongo-ui-docker-context
          path: | 
            frontend/mongo-ui/build/
            frontend/mongo-ui/Dockerfile
            frontend/mongo-ui/nginx.conf
          if-no-files-found: error

  docker-build:
    needs: npm-build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Docker Context artifact
        uses: actions/download-artifact@master
        with:
          name: mongo-ui-docker-context
          path: .

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: ${{secrets.DOCKER_USER}}/mongo-ui:latest

  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "3.16.1"

      - name: Helm Lint
        run: helm lint .
        working-directory: ./frontend/mongo-ui/helm
        
      - name: Helm Template
        run: helm template raspi .
        working-directory: ./frontend/mongo-ui/helm