name: Release Fitness UI

on:
  push:
    tags:
      - 'fitness-ui-[0-9]*\.[0-9]*\.[0-9]*'

concurrency: fitness-ui-release

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASS: ${{secrets.DOCKER_PASS}}
  REPO_NAME: fitness-ui

jobs:
  initialise:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Extract version from the tag
        id: extract_version
        run: |
          VERSION=$(echo "${GITHUB_REF}" | sed -E 's/refs\/tags\/fitness-ui-(.*)/\1/')
          echo "::set-output name=version::$VERSION"
          echo "Extracted version: $VERSION"
  
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: fitness-ui/package-lock.json

      - name: Setup NPM cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('fitness-ui/**') }}
          restore-keys: ${{ runner.os }}-npm-
      
      - name: Install Node dependencies
        working-directory: ./fitness-ui
        run: npm install --legacy-peer-deps

      - name: Build
        working-directory: ./fitness-ui
        run: npm run build

  docker-build:
    needs:
      - npm-build
      - initialise
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:fitness-ui"
          platforms: linux/arm64
          push: true
          tags: ${{env.DOCKER_USER}}/${{env.REPO_NAME}}:${{needs.initialise.outputs.version}}

  helm-package:
    needs: initialise
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "3.16.1"

      - name: Helm Lint
        run: helm lint .
        working-directory: ./fitness-ui/helm
      
      - name: Helm Package
        run: |
          VERSION=${{needs.initialise.outputs.version}}
          helm package . --app-version $VERSION --version $VERSION --destination ./package

      - name: Upload Helm artifact
        uses: actions/upload-artifact@master
        with:
          name: fitness-ui-chart
          path: ./fitness-ui/helm/package
          if-no-files-found: error

  helm-release:
    needs: helm-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout registry
        uses: actions/checkout@v4
        with:
          ref: 'helm-registry'
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: "3.16.1"

      - name: Download Helm artifact
        uses: actions/download-artifact@master
        with:
          name: fitness-ui-chart
          path: ./fitness-ui

      - name: Update and Publish Charts
        shell: bash
        run: |
          echo "Indexing Charts"
          helm repo index . --merge ./index.yaml --url https://raw.githubusercontent.com/irdcat/raspi/helm-registry/
          git config user.name "helm-releaser"
          git config user.email "your-email@example.com"
          git add $(git ls-files -o --exclude-standard)
          git add index.yaml
          git commit -m "Updated ref: $GITHUB_SHA"
          git push