apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{ include "mongo-express.printSharedLabels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
        {{ include "mongo-express.printSharedLabels" . | nindent 8 }}
    spec:
      containers:
        - name: server
          image: mongo-express:{{ .Chart.AppVersion }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config-map
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}